#!/bin/bash
# code-review-multi 批量扫描与 Diff 提取脚本
# 用法: bash code-review-multi-env.sh
# 自动扫描当前目录下所有含 .git 的子仓库，输出聚合 Diff 日志（已过滤生成产物 + autogen 头注释文件）

ROOT_DIR=$(pwd)
ROOT_DIR_NAME=$(basename "$ROOT_DIR")
ALL_DIFFS_TMP="/tmp/batch_git_diff_$(date +%s).txt"
REPO_DIFF_TMP="/tmp/single_repo_diff_$(date +%s).txt"
REPO_DIFF_FILTERED="/tmp/single_repo_diff_filtered_$(date +%s).txt"

# pathspec 排除：编译产物 / lock / 常见 codegen 后缀，统一应用到所有 git diff 调用
EXCLUDES=(
    ':(exclude,glob)**/*.g.dart'
    ':(exclude,glob)**/*.freezed.dart'
    ':(exclude,glob)**/*.pb.dart'
    ':(exclude,glob)**/*.gr.dart'
    ':(exclude,glob)**/*.mocks.dart'
    ':(exclude,glob)**/*.generated.*'
    ':(exclude,glob)**/pubspec.lock'
    ':(exclude,glob)**/package-lock.json'
    ':(exclude,glob)**/yarn.lock'
    ':(exclude,glob)**/Cargo.lock'
    ':(exclude,glob)**/Podfile.lock'
    ':(exclude,glob)**/Pods/**'
    ':(exclude,glob)**/build/**'
    ':(exclude,glob)**/.dart_tool/**'
    ':(exclude,glob)**/.idea/**'
    ':(exclude,glob)**/node_modules/**'
    ':(exclude,glob)**/Generated.swift'
)

# Autogen 头注释过滤 awk 脚本（按 file block 检测前 30 行）
AUTOGEN_AWK='
function is_autogen(b,    n, i, line, lines) {
    n = split(b, lines, "\n")
    for (i = 1; i <= n && i <= 30; i++) {
        line = lines[i]
        if (line ~ /Autogenerated/ ||
            line ~ /AUTO-GENERATED/ ||
            line ~ /auto-generated/ ||
            line ~ /DO NOT EDIT/ ||
            line ~ /GENERATED CODE/ ||
            line ~ /Code generated/ ||
            line ~ /do not modify by hand/ ||
            line ~ /This file is automatically generated/) {
            return 1
        }
    }
    return 0
}
BEGIN { block = ""; in_block = 0 }
/^diff --git / {
    if (in_block && !is_autogen(block)) printf "%s", block
    block = $0 "\n"
    in_block = 1
    next
}
in_block { block = block $0 "\n" }
END {
    if (in_block && !is_autogen(block)) printf "%s", block
}
'

echo "ROOT_DIRECTORY_NAME: $ROOT_DIR_NAME" > "$ALL_DIFFS_TMP"
echo "=========================================" >> "$ALL_DIFFS_TMP"

TOTAL_SCANNED=0
EFFECTIVE_REPOS=0

for d in */; do
    [ -d "$d" ] || continue

    cd "$d" || continue

    if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        cd "$ROOT_DIR"
        continue
    fi

    TOTAL_SCANNED=$((TOTAL_SCANNED + 1))
    REPO_NAME=$(basename "$d")

    C_BR=$(git branch --show-current)

    if [ -z "$C_BR" ]; then
        echo "========== SKIP: $REPO_NAME (原因：当前处于 Detached HEAD 游离状态，无明确分支) ==========" >> "$ALL_DIFFS_TMP"
        cd "$ROOT_DIR"
        continue
    fi

    O_BR=$(git reflog show "$C_BR" | awk '/Created from/ {print $NF; exit}')
    O_BR_COMPARE="${O_BR#remotes/}"
    O_BR_COMPARE="${O_BR_COMPARE#origin/}"

    # 处理 reflog 返回 HEAD 字面量或为空的情况，fallback 到默认主分支
    if [ -z "$O_BR" ] || [ "$O_BR" == "HEAD" ] || [ "$C_BR" == "$O_BR_COMPARE" ]; then
        DEFAULT_BR=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@')
        if [ -z "$DEFAULT_BR" ]; then
            for br in main master develop; do
                if git rev-parse --verify "origin/$br" >/dev/null 2>&1; then
                    DEFAULT_BR="$br"
                    break
                fi
            done
        fi
        if [ -n "$DEFAULT_BR" ]; then
            O_BR="origin/$DEFAULT_BR"
            O_BR_COMPARE="$DEFAULT_BR"
        else
            echo "========== SKIP: $REPO_NAME (原因：未找到源分支且无法匹配默认主分支) ==========" >> "$ALL_DIFFS_TMP"
            cd "$ROOT_DIR"
            continue
        fi
    fi

    if [ "$C_BR" == "$O_BR_COMPARE" ]; then
        echo "========== SKIP: $REPO_NAME (原因：当前分支与源分支一致，无新提交) ==========" >> "$ALL_DIFFS_TMP"
        cd "$ROOT_DIR"
        continue
    fi

    git diff "$O_BR" HEAD -- "${EXCLUDES[@]}" > "$REPO_DIFF_TMP"

    # Autogen 头注释过滤
    awk "$AUTOGEN_AWK" "$REPO_DIFF_TMP" > "$REPO_DIFF_FILTERED"
    mv "$REPO_DIFF_FILTERED" "$REPO_DIFF_TMP"

    if [ -s "$REPO_DIFF_TMP" ]; then
        echo "========== REPOSITORY: $REPO_NAME | BRANCHES: $O_BR -> $C_BR ==========" >> "$ALL_DIFFS_TMP"
        cat "$REPO_DIFF_TMP" >> "$ALL_DIFFS_TMP"
        echo -e "\n\n" >> "$ALL_DIFFS_TMP"
        EFFECTIVE_REPOS=$((EFFECTIVE_REPOS + 1))
    else
        echo "========== SKIP: $REPO_NAME (原因：分支不同但代码无有效改动，或仅自动生成文件变更) ==========" >> "$ALL_DIFFS_TMP"
    fi

    rm -f "$REPO_DIFF_TMP"
    cd "$ROOT_DIR"
done

echo "TOTAL_SCANNED_REPOS: $TOTAL_SCANNED" >> "$ALL_DIFFS_TMP"
echo "EFFECTIVE_REPOS: $EFFECTIVE_REPOS" >> "$ALL_DIFFS_TMP"

# 全仓库均跳过：提前 BLOCK
if [ "$EFFECTIVE_REPOS" -eq 0 ]; then
    echo "BLOCK: 全部 $TOTAL_SCANNED 个仓库均无有效改动（详见上方 SKIP 列表），结束操作。" >> "$ALL_DIFFS_TMP"
fi

cat "$ALL_DIFFS_TMP"
rm -f "$ALL_DIFFS_TMP"
